abstract final class NojinSchema {
  static const version = 5;
  static const createStatements = <String>[
    'CREATE TABLE app_settings (key TEXT NOT NULL PRIMARY KEY, value TEXT NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE notes (id TEXT NOT NULL PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL DEFAULT "", category TEXT NOT NULL DEFAULT "general", is_pinned INTEGER NOT NULL DEFAULT 0, is_archived INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE finance_accounts (id TEXT NOT NULL PRIMARY KEY, name TEXT NOT NULL, account_type TEXT NOT NULL, currency TEXT NOT NULL DEFAULT "toman", balance INTEGER NOT NULL DEFAULT 0, is_archived INTEGER NOT NULL DEFAULT 0, bank_name TEXT, account_number TEXT, card_number TEXT, sheba TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE finance_transactions (id TEXT NOT NULL PRIMARY KEY, account_id TEXT NOT NULL, title TEXT NOT NULL, amount INTEGER NOT NULL, transaction_type TEXT NOT NULL, note TEXT NOT NULL DEFAULT "", occurred_at INTEGER NOT NULL, created_at INTEGER NOT NULL)',
    'CREATE TABLE planning_items (id TEXT NOT NULL PRIMARY KEY, item_type TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT "active", scheduled_at INTEGER, due_at INTEGER, progress REAL NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE info_items (id TEXT NOT NULL PRIMARY KEY, item_type TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL DEFAULT "", is_pinned INTEGER NOT NULL DEFAULT 0, usage_count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE note_media (id TEXT NOT NULL PRIMARY KEY, note_id TEXT NOT NULL, media_type TEXT NOT NULL, file_name TEXT NOT NULL, mime_type TEXT NOT NULL, bytes BLOB NOT NULL, size_bytes INTEGER NOT NULL, duration_ms INTEGER, created_at INTEGER NOT NULL)',
    'CREATE TABLE finance_debts (id TEXT NOT NULL PRIMARY KEY, title TEXT NOT NULL, person_name TEXT NOT NULL, debt_type TEXT NOT NULL, total_amount INTEGER NOT NULL, settled_amount INTEGER NOT NULL DEFAULT 0, currency TEXT NOT NULL DEFAULT "toman", due_at INTEGER, note TEXT NOT NULL DEFAULT "", created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE finance_debt_payments (id TEXT NOT NULL PRIMARY KEY, debt_id TEXT NOT NULL, amount INTEGER NOT NULL, account_id TEXT NOT NULL, transaction_id TEXT NOT NULL, paid_at INTEGER NOT NULL, note TEXT NOT NULL DEFAULT "")',
    'CREATE INDEX finance_debts_status_idx ON finance_debts(debt_type, due_at, settled_amount)',
    'CREATE INDEX finance_debt_payments_debt_idx ON finance_debt_payments(debt_id, paid_at)',
    'CREATE INDEX finance_debt_payments_transaction_idx ON finance_debt_payments(transaction_id)',
    'CREATE TABLE finance_installment_plans (id TEXT NOT NULL PRIMARY KEY, title TEXT NOT NULL, total_amount INTEGER NOT NULL, installment_amount INTEGER NOT NULL, installment_count INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT "toman", first_due_at INTEGER NOT NULL, interval_months INTEGER NOT NULL DEFAULT 1, note TEXT NOT NULL DEFAULT "", created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)',
    'CREATE TABLE finance_installments (id TEXT NOT NULL PRIMARY KEY, plan_id TEXT NOT NULL, sequence INTEGER NOT NULL, due_at INTEGER NOT NULL, amount INTEGER NOT NULL, paid_at INTEGER, transaction_id TEXT)',
    'CREATE INDEX finance_installment_plans_due_idx ON finance_installment_plans(first_due_at)',
    'CREATE INDEX finance_installments_plan_due_idx ON finance_installments(plan_id, due_at)',
    'CREATE INDEX finance_installments_status_idx ON finance_installments(paid_at, due_at)',
    'CREATE INDEX note_media_note_idx ON note_media(note_id, created_at)',
    'CREATE INDEX notes_updated_at_idx ON notes(updated_at)',
    'CREATE INDEX notes_category_idx ON notes(category)',
    'CREATE INDEX notes_archived_pinned_idx ON notes(is_archived, is_pinned)',
    'CREATE INDEX finance_accounts_updated_at_idx ON finance_accounts(updated_at)',
    'CREATE INDEX finance_transactions_account_date_idx ON finance_transactions(account_id, occurred_at)',
    'CREATE INDEX finance_transactions_date_idx ON finance_transactions(occurred_at)',
    'CREATE INDEX planning_items_type_status_idx ON planning_items(item_type, status)',
    'CREATE INDEX planning_items_due_at_idx ON planning_items(due_at)',
    'CREATE INDEX info_items_type_idx ON info_items(item_type)',
    'CREATE INDEX info_items_usage_idx ON info_items(usage_count)',
    'CREATE INDEX info_items_updated_at_idx ON info_items(updated_at)',
  ];
  static const tableNames = <String>['app_settings','notes','finance_accounts','finance_transactions','planning_items','info_items','note_media','finance_debts','finance_debt_payments','finance_installment_plans','finance_installments'];
}
